#!/usr/bin/env bash

keep_asm=false
run_program=false
while getopts "ar" opt; do
    case $opt in
        a) keep_asm=true ;;
        r) run_program=true ;;
    esac
done
shift $((OPTIND - 1))
target/debug/minicompiler "$1" TEMP.s
as -o TEMP.o TEMP.s
gcc -o "$2" TEMP.o
rm TEMP.o
if [ "$keep_asm" = false ]; then
    rm TEMP.s
fi
if [ "$run_program" = true ]; then
    ./"$2"
fi
