#!/usr/bin/env bash

keep_asm=false

while getopts "a" opt; do
    case $opt in
        a) keep_asm=true ;;
    esac
done
shift $((OPTIND - 1))

target/debug/minicompiler "$1" TEMP.s
as -o TEMP.o TEMP.s
gcc -o "$2" TEMP.o

rm TEMP.o
if [ "$keep_asm" = false ]; then
    rm TEMP.s
fi
