#!/usr/bin/env bash

BUILD=true

while [[ $# -gt 0 ]]; do
    case $1 in
        -n) BUILD=false; shift ;;
    esac
done

# Sync mac -> pi
rsync -av --exclude "target" "$MAC_YUM/" "$PI_YUM/"

if [[ "$(hostname)" == "mac" ]]; then
    if $BUILD; then
        ssh pi -t "source ~/.zshrc && cd ~/programming_projects/minicompiler && cargo build && ./scripts/yute -n && exec \$SHELL"
    else
        ssh pi -t "source ~/.zshrc && cd ~/programming_projects/minicompiler && ./scripts/yute -n && exec \$SHELL"
    fi
else
    PROJECT=~/programming_projects/minicompiler
    cd $PROJECT
    source ./scripts/common
    $BUILD && cargo build

    failures=()

    for t in primetest nonparam_func long_ass_binop; do
        ex_path=$(compile_yum "./tests" "$t")
        
        "$ex_path"
        exit_code=$?

        if [ $exit_code -ne 1 ]; then
            failures+=("$t (exit code: $exit_code)")
        fi
    done

    echo ""
    echo "================================"
    if [ ${#failures[@]} -eq 0 ]; then
        echo "All tests passed!"
    else
        echo "FAILURES (${#failures[@]}):"
        for f in "${failures[@]}"; do
            echo "  - $f"
        done
        exit 1
    fi
fi
